# Generated by Django 5.2.4 on 2025-07-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work'), ('Shopping', 'Shopping'), ('Study', 'Study'), ('Other', 'Other')], default='Personal', max_length=20),
        ),
    ]
